---
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: "hitch.email.1.0.event.email.sent"
          binder: "local_rabbit"
        input:
          destination: "hitch.accounts.1.0.event.user.signup"
          binder: "local_rabbit"
      binders:
        local_rabbit:
          type: "rabbit"
          environment:
            spring:
              password: "guest"
              port: "5672"
              host: "localhost"
              virtual-host: "/"
              username: "guest"
          inheritEnvironment: true
          defaultCandidate: true
